## Neural Network implementation

In [1]:
import numpy as np 
import pandas as pd 
import tensorflow as tf

In [51]:
dataset = pd.read_csv('insurance_data.csv')


In [52]:
# X = dataset.iloc[:, 0:-1].values
# y = dataset.iloc[:, -1].values

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test,  y_train, y_test = train_test_split(dataset[['age','affordibility']], dataset.bought_insurance, test_size=0.2, random_state=21)

In [55]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [56]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

In [57]:
model = tf.keras.Sequential([
  tf.keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

c:\Users\dabhi\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [58]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=150)

Epoch 1/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 857ms/step - accuracy: 0.5000 - loss: 15.5909
Epoch 2/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 15.5748
Epoch 3/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 15.5587
Epoch 4/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 15.5426
Epoch 5/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5000 - loss: 15.5265
Epoch 6/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 15.5105
Epoch 7/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 15.4944
Epoch 8/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 15.4783
Epoch 9/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 15.4622
Epoch 10/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 15.4461
Epoch 11/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 15.4300
Epoch 12/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy:

In [69]:
model.evaluate(X_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - accuracy: 0.5000 - loss: 0.6301


[0.6301482319831848, 0.5]

In [70]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step


array([[0.51562035],
       [0.70651203],
       [0.7388507 ],
       [0.7642286 ],
       [0.589041  ],
       [0.517743  ]], dtype=float32)

In [61]:
y_test

1     0
20    0
22    1
5     1
7     1
21    0
Name: bought_insurance, dtype: int64

In [62]:
coef, intercept = model.get_weights()
coef, intercept

(array([[0.85000193],
        [0.85000193]], dtype=float32),
 array([-0.14999887], dtype=float32))

In [63]:
def sigmoid(x):
        import math
        return 1 / (1 + math.exp(-x))

In [64]:
def prediction_function(age, affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

In [65]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

In [66]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [67]:
class myNN:
    def __init__(self):
        self.w1 = 1 
        self.w2 = 1
        self.bias = 0
        
    def fit(self, X, y, epochs, loss_thresold):
        self.w1, self.w2, self.bias = self.gradient_descent(X['age'],X['affordibility'],y, epochs, loss_thresold)
        print(f"Final weights and bias: w1: {self.w1}, w2: {self.w2}, bias: {self.bias}")
        
    def predict(self, X_test):
        weighted_sum = self.w1*X_test['age'] + self.w2*X_test['affordibility'] + self.bias
        return sigmoid_numpy(weighted_sum)

    def gradient_descent(self, age,affordability, y_true, epochs, loss_thresold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)
        for i in range(epochs):
            weighted_sum = w1 * age + w2 * affordability + bias
            y_predicted = sigmoid_numpy(weighted_sum)
            loss = log_loss(y_true, y_predicted)
            
            w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
            w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

            bias_d = np.mean(y_predicted-y_true)
            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            bias = bias - rate * bias_d
            
            if i%50==0:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
            
            if loss<=loss_thresold:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
                break

        return w1, w2, bias

In [71]:
customModel = myNN()
customModel.fit(X_train_scaled, y_train, epochs=8000, loss_thresold=0.4631)

Epoch:0, w1:0.9711839813918843, w2:0.9344592973345814, bias:-0.12258403253473343, loss:0.730437847331664
Epoch:50, w1:1.4646618672709728, w2:1.1294216167288662, bias:-1.324174949217393, loss:0.5639860959204603
Epoch:100, w1:2.12762529443882, w2:1.3953537642590041, bias:-1.823698511854564, loss:0.5331871974056395
Epoch:150, w1:2.750315469396105, w2:1.5313377548753198, bias:-2.1978729162923547, loss:0.5111876156203473
Epoch:200, w1:3.3260997236531327, w2:1.6059450655287049, bias:-2.500177923942103, loss:0.49396710616558975
Epoch:250, w1:3.8548028846197524, w2:1.65025164310657, bias:-2.7567597218415316, loss:0.4800188940343979
Epoch:300, w1:4.338939261253546, w2:1.6793393891797521, bias:-2.9816466799489105, loss:0.4685449842278045
Epoch:328, w1:4.591896850752983, w2:1.6919904276780868, bias:-3.0969061528437236, loss:0.46299760238377685
Final weights and bias: w1: 4.591896850752983, w2: 1.6919904276780868, bias: -3.0969061528437236
